#! /bin/sh

echo "Choosing a random wallpaper.."
wall=$(find $HOME/Pictures/Wall -type f | shuf -n 1)
echo "Setting up wallpaper.."
# xwallpaper --zoom $wall
feh --bg-fill $wall
echo "Generating pywal color schemes.."
wal -i $wall >/dev/null
echo "Recompiling dwm with new colors.."
(cd $HOME/.config/suckless/dwm && sudo make clean install>/dev/null)

echo "^_^ Restart dwm for new look!"
